[package]
name = "day-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew="0.19.3"
gloo="0.8.0"
stylist={version="0.10.1",features=["yew"]}
#serde="1.0.147"
#serde_json="1.0.87"